twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        tmdb_images_original: https://image.tmdb.org/t/p/w780
        tmdb_images_w154: https://image.tmdb.org/t/p/w154

when@test:
    twig:
        strict_variables: true
